### PR TITLE
Msg view path

### PR DESCRIPTION
**Pull request by marino-gnss**
Issue: 

- Message text from message.json not loaded when running installer

Root cause: 

- Expected file path for message.json incorrect

Changes: 
- correction to file path of message.json
- updated required dependency file

JIRA: PTPD-27107

### CODE REVIEW

**Review by dhodges-spirent — CHANGES_REQUESTED** [review]
@marino-gnss I am not sure all the files that were changed would pass for upstream. I was expecting just the message.py to be committed and merged.

**Comment by marino-gnss** [comment]
@dhodges-spirent 
I could revert the requirements list to the previous state.  The reason for this was that if you run make clean, a dependency was missing.

Also for the *.po files was not really sure how to handle those.

**Comment by dhodges-spirent** [comment]
@marino-gnss keeping the apt-deps.txt makes sense then, but reverting the po files would be good.

**Comment by marino-gnss** [comment]
@dhodges-spirent just looking again through the changes, there are quite a few files beyond the *.po that looks changes that I did not change myself.  I don't know why that occurs actually

**Comment by marino-gnss** [comment]
@dhodges-spirent ignore the last comment I made, it is only the PO folder that automatically changed.

**Comment by marino-gnss** [comment]
@dhodges-spirent I have reverted the po/*.po files

**Review by dhodges-spirent — APPROVED** [review]
Looks good

**Pull request merged**
